name: u1r
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  get: ^4.6.6
  get_storage: ^2.1.1
  url_launcher: ^6.2.2
  intl: ^0.19.0
  # Utility Packages
  http: ^1.1.0
  logger: ^2.0.1

  smooth_page_indicator: ^1.1.0
  
  badges: ^3.1.2
  otp_text_field: ^1.1.3
  




  #for special effects
  modal_progress_hud_nsn: ^0.4.0
  # Product Specific
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2
  connectivity_plus: ^5.0.2
  firebase_auth: ^4.15.3
  firebase_storage: ^11.5.6
  cloud_firestore: ^4.13.6
 
  flutter_native_splash: ^2.3.1
  firebase_app_check: ^0.2.1+8
 
  lottie: ^2.7.0
  firebase_core: ^2.24.2
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  mongo_dart: ^0.10.0
  go_router: ^13.2.0
 
  
flutter_native_splash: 
  android: true
  ios: true
  web: false


  color: "#FFFFFF"
  color_dark: "#272727"
  image: assets/logo/U1R-logos_black.png
  image_dark: assets/logo/U1R-logos_transparent.png

  android_12:
    color: "#FFFFFF"
    color_dark: "#272727"
    image: assets/logo/U1R-logos_black.png
    image_dark: assets/logo/U1R-logos_transparent.png
 

dev_dependencies:

  flutter_launcher_icons: "^0.13.1"
  
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-icon/app-icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
   
    - assets/icons/menu.png
    - assets/icons/menu.ico
    - assets/icons/menu.svg
    - assets/logo/google-logo.png
    - assets/logo/fb-logo.png
    - assets/logo/U1R-logos_black.png
    - assets/images/onboarding_images/sammy-line-delivery.gif
    - assets/images/onboarding_images/sammy-line-no-connection.gif
    - assets/images/onboarding_images/sammy-line-searching.gif
    - assets/images/onboarding_images/sammy-line-shopping.gif
    - assets/images/animations/sammy-line-workout.gif
    - assets/images/animations/sammy-line-sale.png
    - assets/images/animations/sammy-line-success.png
    - assets/images/animations/sammy-line-come-back-later.png
    - assets/images/animations/sammy-line-man-receives-a-mail.png
    - assets/images/animations/sammy-line-man-receives-a-mail.png
    - assets/images/animations/141594-animation-of-docer.json
    - assets/images/animations/72462-check-register.json
    # category Images
    - assets/images/category_images/dry_fruits.png
    - assets/images/category_images/whole_spices.png
    - assets/images/category_images/ground_spices.png
    - assets/images/category_images/sundried_fruits.jpg
    - assets/images/category_images/chemicals_food.png
    - assets/images/category_images/cleaning materials.png
    - assets/images/category_images/dates.jpeg
    - assets/images/category_images/ghee.jpg
    - assets/images/category_images/flavoured dry fruits.png
    - assets/images/category_images/oils.jpeg
    - assets/images/animations/emptycartanimation.json    
     #Banner Images
    - assets/images/category_images/banneriamge1.jpg
    - assets/images/category_images/banneriamge2.jpg
    - assets/images/category_images/banneriamge3.jpg
      #default profile image url
    - assets/images/category_images/default-avatar.png
    - assets/images/animations/seetingup-for-first-time.json
    - assets/images/animations/onboarding/Animation - 1704258245475.json
    - assets/images/animations/onboarding/Animation - 1704258349310.json
    - assets/images/animations/onboarding/Animation - 1704258382135.json
     #payment method Images
    - assets/images/payment-method/phonepe.png
    - assets/images/payment-method/Paytm_Logo.jpg


  fonts:
    - family : Poppins
      fonts :
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight : 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight : 400

        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style : italic
        
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight : 500
        
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          style: italic 
          weight : 500
        
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight : 600

        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight : 800
          
